server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/customer
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672 # can also be amqp://guest@127.0.0.1:5672/ instead of localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true